### ISSUE TITLE
`select_on_execution` not working as expected for some inputs on `Switch (Any)` custom node.

### ISSUE THREAD

**Issue by abhinavzspace** [ltdrdata/ComfyUI-extension-tutorials#53]
Last example [here](https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/switch.md) does not work as expected.

When `sel_mode` is set to `select_on_execution` and `select` input is set to "1" for both the nodes, the `Switch (Any)` node does not let the image show as output.

<img width="1401" alt="Screenshot 2024-09-01 at 1 51 13 PM" src="https://github.com/user-attachments/assets/32cbddaf-e622-4209-a30c-623e79690172">

Though it works as expected when "2" is set.

<img width="1295" alt="Screenshot 2024-09-01 at 1 56 51 PM" src="https://github.com/user-attachments/assets/ec65ebbb-ee1f-48e3-94ee-87435685f8b6">

**Comment by ltdrdata** [comment]
I've investigated this, and due to the current limitations of the execution model, if execution blocking is transmitted to some of the nodes connected by switch (any), the switch (any) itself also stops working.

For now, it seems that you need to control it in a way that uses only one of the two options.

![image](https://github.com/user-attachments/assets/00a677ab-e0ce-40a0-b3ce-da6b0afebda1)

When attempting to control the execution of some workflows through `Switch (any)`, it's important to note that you shouldn't add output nodes like PreviewImage to the intermediate nodes.

While `Switch (any)` will only execute the sub-workflow connected to the selected input, `PreviewImage` will execute that part of the workflow for itself, regardless of the `Switch (any)` node.

This is where it differs from the `Inversed Switch`, which has the effect of blocking execution further down the line.

**Comment by ltdrdata** [comment]
Current Execution System is little bit tricky.

If you mute (or remove) `PreviewImage` nodes like this.
It works well.

![select_on_execution](https://github.com/user-attachments/assets/785f9071-2c16-474b-a4c6-56e832a2c644)

The reason for this is the same as explained earlier: if you attach a PreviewImage node, it forcibly triggers the path that causes an Execution block, which then affects the `Switch (any)`.

However, in cases where there is no `PreviewImage` node, the blocking by `Switch (any)` takes precedence, protecting the `Switch (any)` node from being affected.

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/switch.md#sel_mode

The tutorial is updated.

**Comment by abhinavzspace** [comment]
Thank you @ltdrdata 

I am trying to use this process in my workflow.

I have conditionally divided my workflow, to do a face swap and not to. In the case of "no face swap", output1 is directly connected to input1 and it works good. But in the case of "face swap", where the chain is a bit long, there are instantid nodes, ipadapter nodes, etc, it does not work. **I have removed all the preview nodes and some nodes which did not seem to have any output.** Still its not working.

I really need to make it work. Any help is appreciated.

Thanks!

**Comment by ltdrdata** [comment]
> Thank you @ltdrdata
> 
> I am trying to use this process in my workflow.
> 
> I have conditionally divided my workflow, to do a face swap and not to. In the case of "no face swap", output1 is directly connected to input1 and it works good. But in the case of "face swap", where the chain is a bit long, there are instantid nodes, ipadapter nodes, etc, it does not work. **I have removed all the preview nodes and some nodes which did not seem to have any output.** Still its not working.
> 
> I really need to make it work. Any help is appreciated.
> 
> Thanks!

In addition to preview nodes, there may also be output nodes included within it.
The reason for removing the Preview node is that an Output node acts as a terminal node by itself, forcing the connection up to that node to trigger regardless of the rest of the workflow.

**Comment by abhinavzspace** [comment]
I was not able to figure out the output nodes.

I tried `If` and `universal switch` nodes from [https://github.com/VykosX/ControlFlowUtils](https://github.com/VykosX/ControlFlowUtils). That did it. It's working even with preview nodes.

Thanks
